---
- name: install java (openjdk)
  yum: name=java-1.8.0-openjdk state=present

- name: create user for running app
  user: name="{{ app_user }}" shell=/bin/bash state=present

- name: ensure log dir exists
  file:
    path: "/var/log/{{ app_user }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: place nginx config
  template: src=etc/nginx/conf.d/app.conf.j2 dest=/etc/nginx/conf.d/app.conf backup=yes
  notify:
    - check nginx configuration
    - restart nginx

- name: deploy application
  command: cp "/vagrant/app/build/libs/homework-{{ app_version }}.jar" /home/{{ app_user }}/homework-{{ app_version }}.jar
  # creates: /home/{{ app_user }}/homework-{{ app_version }}.jar

- name: create superuserd profile for app
  template: src=etc/supervisord.d/app.ini.j2 dest=/etc/supervisord.d/app.ini backup=yes
  notify:
    - restart app

- name: ensure application is loaded
  supervisorctl: name=app state=present

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
