---
- name: check nginx configuration
  shell: "nginx -t -c /etc/nginx/nginx.conf"

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=8 tw=0 :
