---
- name: install nginx
  yum: name=nginx state=latest
  tags:
    - nginx:install

- name: ensure nginx is enabled at startup
  service: name=nginx enabled=yes
  tags:
    - nginx:service

- name: configure main nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    force: yes
  notify:
    - check nginx configuration
    - restart nginx
  tags:
    - nginx:config:main

- name: configure nginx status
  template: src=etc/nginx/conf.d/status.conf.j2 dest=/etc/nginx/conf.d/status.conf
  notify:
    - check nginx configuration
    - restart nginx
  tags:
    - nginx:config:status

- name: create zabbix_agentd.d directory
  file: path=/etc/zabbix/zabbix_agentd.d state=directory
  tags:
    - nginx:zabbix

- name: place nginx params for zabbix-agent
  copy: src=etc/zabbix/zabbix_agentd.d/nginx-params.conf dest=/etc/zabbix/zabbix_agentd.d/nginx-params.conf
  tags:
    - nginx:zabbix:params

- name: place nginx status check script
  template: src=usr/local/bin/nginx-check.sh.j2 dest=/usr/local/bin/nginx-check.sh mode=a+x
  tags:
    - nginx:zabbix:check

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=8 tw=0 :
